version: '3'
services: 
  
  redis-server:
    image: 'redis'

  contact-app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      -  "3000:3000" 
    volumes:
      - /contact-app/node_modules
      - .:/contact-app
