version: '3'
services: # Containers
  
  # Redis container
  redis-server:
    image: 'redis'

  # Web app container
  contact-app:
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      -  "3000:3000" 
    volumes:
      - /contact-app/node_modules
      - .:/contact-app
  
  # Test container
  test:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /contact-app/node_modules
      - .:/contact-app
    command: ["npm","test"]  